#!/bin/bash
# Quick Start Commands for Headless Environment Testing

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║  Cardano Mine - Headless Environment Quick Start              ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""

# Check if we're in the right directory
if [ ! -f "package.json" ]; then
    echo "❌ Error: package.json not found"
    echo "Please run this script from the Node-electronUI directory"
    exit 1
fi

echo "✅ Found Node-electronUI project"
echo ""
echo "Available commands:"
echo ""
echo "1️⃣  SETUP - Install dependencies and build"
echo "   npm install && npm run build"
echo ""
echo "2️⃣  GENERATE CHALLENGE - Create a signing challenge"
echo "   npm run cli:challenge -- --community 'cardano-devs-ph' --action 'voting'"
echo ""
echo "3️⃣  VERIFY SIGNATURE - Check if a signature is valid"
echo "   npm run cli:verify -- --pubkey 'a0a1a2a3...' --message 'Hello' --signature 'b0b1b2b3...'"
echo ""
echo "4️⃣  BATCH VERIFY - Process multiple signatures"
echo "   npm run cli:batch -- --file batch-verify-example.json --action verify"
echo ""
echo "5️⃣  GENERATE REPORT - Export data as CSV/JSON/HTML"
echo "   npm run cli:report -- --type user_registry --format json"
echo ""
echo "6️⃣  BUILD ONLY (no GUI)"
echo "   npm run build"
echo ""
echo "7️⃣  WATCH & BUILD (auto-rebuild on changes)"
echo "   npm run watch"
echo ""
echo "8️⃣  GUI MODE (only on machines with display)"
echo "   npm run dev"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📖 For detailed information, see:"
echo "   • START_HERE.md - Navigation guide"
echo "   • TESTING_GUIDE.md - Complete testing instructions"
echo "   • HEADLESS_FIX_SUMMARY.md - Headless environment details"
echo "   • README.md - Full API reference"
echo ""
echo "🚀 Quick test (try this first):"
echo "   npm install && npm run build && npm run cli:challenge -- --community 'test'"
echo ""
